plugin: yacloud_compute
yacloud_token_file: .oauth.token
yacloud_clouds:
  - cloud-svkoval67
yacloud_folders:
  - default
yacloud_group_label: group
ansible_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
